### ISSUE TITLE
Swift: Xcode 16 - Library not loaded: @rpath/libSwiftSyntax.dylib

### ISSUE THREAD

**Issue by weisunOW** [github/codeql#17819]
We recently updated our iOS project to build with Xcode 16, swift 5 mode (`SWIFT_VERSION = 5`). However our Azure CodeQL pipeline started to fail on database creation with `Library not loaded: @rpath/libSwiftSyntax.dylib` error for both `WidgetExtension` and `IntentsExtension`.

We've tried different CodeQL versions: 2.18.0, 2.19.1, 2.19.2, all failed with the same error. The same command worked when we built with Xcode 15.4, unfortunately we cannot fallback to Xcode 15.4 now.

Here is the database create command, please note that `.codeql.yml` is currently empty.
`codeql database create -l swift codeql-database --threads 0 --codescanning-config .codeql.yml --command \"${WORKSPACE_DIR}/Scripts/ci/az-build-for-codeql.sh\"`

The `--command` build script runs `xcodebuild` command below, the build script itself builds correctly without CodeQL cli. 
`xcodebuild -workspace App.xcworkspace -scheme Application -derivedDataPath Build/DerivedData -destination "OS=18.0,name=iPhone 16 Pro Max"`

Here is the failure part of the build log, sorry we cannot share the full log due to our policy. The log suggests that `libSwiftSyntax.dylib` cannot be found in the listed paths, however I'm sure that `libSwiftSyntax.dylib` come as part of Xcode 16 under `/Application/Xcode.app/Content/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host`. Please advise if we have missed anything?
```Shell
[2024-10-22 13:32:15] [build-stdout] ExtractAppIntentsMetadata (in target 'IntentsExtension' from project 'App')
[2024-10-22 13:32:15] [build-stdout]     cd /Users/devops/azure-agent-0/_work/20/s/App
[2024-10-22 13:32:15] [build-stdout]     /Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/appintentsmetadataprocessor --output /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Products/Debug-iphonesimulator/IntentsExtension.appex --toolchain-dir /Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain --module-name IntentsExtension --sdk-root /Applications/Xcode-16.0.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk --xcode-version 16A242d --platform-family iOS --deployment-target 15.0 --bundle-identifier au.com.app.mobile.dev.intentsextension --target-triple arm64-apple-ios15.0-simulator --binary-file /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Products/Debug-iphonesimulator/IntentsExtension.appex/IntentsExtension --dependency-file /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/IntentsExtension.build/Objects-normal/arm64/IntentsExtension_dependency_info.dat --stringsdata-file /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/IntentsExtension.build/Objects-normal/arm64/ExtractedAppShortcutsMetadata.stringsdata --source-file-list /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/IntentsExtension.build/Objects-normal/arm64/IntentsExtension.SwiftFileList --metadata-file-list /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/IntentsExtension.build/IntentsExtension.DependencyMetadataFileList --swift-const-vals-list /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/IntentsExtension.build/Objects-normal/arm64/IntentsExtension.SwiftConstValuesFileList --compile-time-extraction --deployment-aware-processing --validate-assistant-intents
[2024-10-22 13:32:15] [build-stdout] dyld[61317]: Library not loaded: @rpath/libSwiftSyntax.dylib
[2024-10-22 13:32:15] [build-stdout]   Referenced from: <02FDFF53-8DFD-3994-86CB-405776B79E9A> /Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/AppIntentsSupport.framework/Versions/A/AppIntentsSupport
[2024-10-22 13:32:15] [build-stdout]   Reason: tried: '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/Frameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/AppIntentsSupport.framework/Versions/A/Frameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/AppIntentsSupport.framework/Versions/A/../Frameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/AppIntentsMetadataExtractor.framework/Versions/A/../../../libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/Frameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/Frameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Frameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../Frameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../Frameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../PlugIns/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../PlugIns/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../Frameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../Frameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../Pl
[2024-10-22 13:32:15] [build-stdout] ugIns/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../PlugIns/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file)
[2024-10-22 13:32:15] [build-stdout] Command ExtractAppIntentsMetadata failed with a nonzero exit code
[2024-10-22 13:32:15] [build-stdout] ExtractAppIntentsMetadata (in target 'WidgetExtension' from project 'App')
[2024-10-22 13:32:15] [build-stdout]     cd /Users/devops/azure-agent-0/_work/20/s/App
[2024-10-22 13:32:15] [build-stdout]     /Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/appintentsmetadataprocessor --output /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Products/Debug-iphonesimulator/WidgetExtension.appex --toolchain-dir /Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain --module-name WidgetExtension --sdk-root /Applications/Xcode-16.0.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk --xcode-version 16A242d --platform-family iOS --deployment-target 15.0 --bundle-identifier au.com.app.mobile.dev.widgetextension --target-triple arm64-apple-ios15.0-simulator --binary-file /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Products/Debug-iphonesimulator/WidgetExtension.appex/WidgetExtension --dependency-file /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/WidgetExtension.build/Objects-normal/arm64/WidgetExtension_dependency_info.dat --stringsdata-file /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/WidgetExtension.build/Objects-normal/arm64/ExtractedAppShortcutsMetadata.stringsdata --source-file-list /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/WidgetExtension.build/Objects-normal/arm64/WidgetExtension.SwiftFileList --metadata-file-list /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/WidgetExtension.build/WidgetExtension.DependencyMetadataFileList --swift-const-vals-list /Users/devops/azure-agent-0/_work/20/s/Build/DerivedData/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/WidgetExtension.build/Objects-normal/arm64/WidgetExtension.SwiftConstValuesFileList --compile-time-extraction --deployment-aware-processing --validate-assistant-intents
[2024-10-22 13:32:15] [build-stdout] dyld[61318]: Library not loaded: @rpath/libSwiftSyntax.dylib
[2024-10-22 13:32:15] [build-stdout]   Referenced from: <02FDFF53-8DFD-3994-86CB-405776B79E9A> /Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/AppIntentsSupport.framework/Versions/A/AppIntentsSupport
[2024-10-22 13:32:15] [build-stdout]   Reason: tried: '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/Frameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/AppIntentsSupport.framework/Versions/A/Frameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/AppIntentsSupport.framework/Versions/A/../Frameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/AppIntentsMetadataExtractor.framework/Versions/A/../../../libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/Frameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/Frameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Frameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libSwiftSyntax.dylib' (no such file), '/Users/devops/azure-agent-0/_work/20/s/codeql-database/working/copy-root/000001F6/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../Frameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../Frameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../PlugIns/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../PlugIns/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../PrivateFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../Frameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../Frameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../SharedFrameworks/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../Pl
[2024-10-22 13:32:15] [build-stdout] ugIns/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../PlugIns/libSwiftSyntax.dylib' (no such file), '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file)
[2024-10-22 13:32:15] [build-stdout] Command ExtractAppIntentsMetadata failed with a nonzero exit code
```
```Shell
[2024-10-22 15:30:53] [build-stderr] ** BUILD FAILED **
[2024-10-22 15:30:53] [build-stderr] The following build commands failed:
[2024-10-22 15:30:53] [build-stderr] 	ExtractAppIntentsMetadata (in target 'IntentsExtension' from project 'App')
[2024-10-22 15:30:53] [build-stderr] 	ExtractAppIntentsMetadata (in target 'WidgetExtension' from project 'App')
[2024-10-22 15:30:53] [build-stderr] 	Building workspace App with scheme Application
[2024-10-22 15:30:53] [build-stderr] (3 failures)
[2024-10-22 15:30:53] [ERROR] Spawned process exited abnormally (code 65; tried to run: [/Users/devops/Developer/codeql/tools/osx64/preload_tracer, /Users/devops/azure-agent-0/_work/20/s/Scripts/ci/az-build-for-codeql.sh])
```

**Comment by coadaflorin** [comment]
@weisunOW thanks for reporting this! 
Currently we do not support scanning Swift code when using Xcode16, but we are working on adding support. We are currently investigating this and will post an update when we have something you can test.

**Comment by weisunOW** [comment]
Hi @coadaflorin, I tried the new v2.20.0 CodeQL CLI, I'm still seeing the same error.

**Comment by coadaflorin** [comment]
Hi @weisunOW,  we had to accelerate the release of `2.20.0` to get some updates out and that meant we did not get a chance to merge in the changes that add support for Xcode 16 / Swift 6.0. We will add these in the next release which is currently estimated shortly after the new year. Thank you for your patience and feel free to tag me if you have more questions on the topic.

**Comment by cbieniakTU** [comment]
Hi @coadaflorin, We're seeing the same issue on Xcode 16 using 2.20.1.

```
'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../XcodeDefault.xctoolchain/usr/lib/libSwiftSyntax.dylib' (no such file), 
```

**Comment by weisunOW** [comment]
Hi @coadaflorin @cbieniakTU, we confirmed that the workaround https://github.com/github/codeql-action/issues/2506#issuecomment-2594033147 by @jsm174 worked for us.

**Comment by redsun82** [comment]
Hi all! I was able to reproduce this locally and I am working on a solution. In the meantime, the [workaround mentioned above](https://github.com/github/codeql-action/issues/2506#issuecomment-2594033147) is probably the best way to get around this issue.

**Comment by redsun82** [comment]
Sorry, I closed this by mistake. We do however have a change that should fix this coming up in the next release later this week, so stay tuned 👍

**Comment by stefanrenne** [comment]
@redsun82 any update on this issue? is resolving this issue also in scope for microsoft devops?

**Comment by redsun82** [comment]
A fix for what we were able to reproduce is included in the latest 2.20.3 release that was made available on the 24th of January.

**Comment by coadaflorin** [comment]
@stefanrenne yes, they both use the same CodeQL engine, so as soon as the devops platform picks up the latest version as suggested above, the problem should be fixed.

**Comment by coadaflorin** [comment]
@stefanrenne can you confirm if this fixed your problem? I will close this issue as I haven't seen any follow-up from anyone that things are not working. If you are still seeing this issue on a recent version feel free to reopen this ticket.

**Comment by jsm174** [comment]
I just attempted to remove the hack from our pipeline, and it failed as well with the same error. It looks like it pulled 2.20.4.

**Comment by stefanrenne** [comment]
@coadaflorin I just tried 2.20.5 on devops and it gives me the same error as before, see attached logs

[logs.txt](https://github.com/user-attachments/files/18905546/logs.txt)

**Comment by redsun82** [comment]
:wave: I'm sorry this was not fixed the first time around 🙇 

Our first fix consisted in skipping tracing for the `appintentsnltrainingprocessor` which is what seemed causing the problems in our internal reproduction tests. However, the problem persisted for the related `appintentsmetadataprocessor` binary.

We've now added on our `main` branch a fix that adds the new offending binary (and another related `appshortcutstringsprocessor` one) to our exclusion list of tracing on macOS, and also introduced a configuration mechanism for it, by providing regex patterns in a `CODEQL_TRACER_RELOCATION_EXCLUDE` environment variable. This will allow to exclude further binaries this problem may arise with.

The above will land in a release around the 4th of April.

**Comment by stefanrenne** [comment]
@redsun82 just tested codeql bundle 2.21.0 with Xcode 16.2 in ADO using the following task
```
 - task: AdvancedSecurity-Codeql-Init@1
  inputs:
    enableAutomaticCodeQLInstall: true
    languages: swift
    querysuite: security-and-quality
- task: Xcode@5
  displayName: 'Build and archive'
  inputs:
    configuration: 'ANONYMISED'
    sdk: iphoneos
    xcWorkspacePath: ANONYMISED.xcodeproj
    scheme: 'ANONYMISED'
    xcodeVersion: specifyPath
    xcodeDeveloperDir: '/Applications/Xcode_$(xcodeVersion).app/Contents/Developer'
    packageApp: true
    archivePath: 'output/release'
    exportPath: 'output/release'
    exportOptions: plist
    exportOptionsPlist: 'Signing/$(buildType)/exportOptions.plist'
    signingOption: default
    args: '-clonedSourcePackagesDirPath "SourcePackages"'
```
and for me it still doesn't work, see attached logging

[logging.txt](https://github.com/user-attachments/files/19631852/logging.txt)
